version: '3.8'

services:
  backend:
    container_name: backend-user-recht-tool
    image: guellaomar/backend-user-recht-tool:latest
    build:
      context: .
      dockerfile: backend/src/main/docker/Dockerfile.azure
    ports:
      - "9000:9000"
    depends_on:
      - backenddb
    networks:
      - mynetwork

  auditlogs:
    container_name: auditlogs
    image: guellaomar/auditlogs:latest
    build:
      context: .
      dockerfile: auditLogs/src/main/docker/Dockerfile.azure
    ports:
      - "9001:9001"
    depends_on:
      - logsdb
    networks:
      - mynetwork

  backenddb:
    container_name: backenddb
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=userrechttool
      - POSTGRES_DB=userrechttooldb
    networks:
      - mynetwork

  logsdb:
    container_name: logsdb
    image: postgres:latest
    restart: always
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=auditlog
      - POSTGRES_DB=auditlogdb
    command:
      -p 5433

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
